#!/bin/bash -e

STARTSHELL=
CONFFILE=
PACKAGES=()
AUR=()

usage() {
    echo "usage: $0 [-c conf | -s] dir" >&2
    exit 1
}

while getopts 'c:s' arg; do
    case $arg in
	c)
	    CONFFILE=$OPTARG
	    ;;
	s)
	    STARTSHELL=1
	    ;;
	\?)
	    usage
	    ;;
    esac
done

[[ $# -eq $((OPTIND)) ]] || usage
shift $((OPTIND - 1))
BASEDIR=$1
[[ $BASEDIR != /* ]] && BASEDIR="$(pwd)/$BASEDIR"
DESTDIR="$BASEDIR/root"
READONLY="$BASEDIR/readonly"

[[ -z $CONFFILE ]] || . $CONFFILE

umask 022

RCCONF="$DESTDIR/etc/rc.conf"

MOUNTED=()
cleanup() {
    set +e
    trap - 0
    local n=${#MOUNTED[@]}
    while [[ $n -gt 0 ]]; do
	n=$((n - 1))
	umount -l "${MOUNTED[$n]}"
	unset MOUNTED[$n]
    done
    exit
}

bind_dirs() {
    trap 'cleanup' 0 2 15

    for dir in /proc /sys /dev /dev/pts /dev/shm; do
	mkdir -p "$DESTDIR/${dir#/}"
	MOUNTED[${#MOUNTED[@]}]="$DESTDIR/${dir#/}"
	mount -B "$dir" "$DESTDIR/${dir#/}"
    done

    mkdir -p "$DESTDIR"/tmp
    MOUNTED[${#MOUNTED[@]}]="$DESTDIR"/tmp
    mount -t tmpfs tmpfs "$DESTDIR"/tmp
}

bind_files() {
    for file in /etc/resolv.conf /etc/pacman.d/mirrorlist; do
	MOUNTED[${#MOUNTED[@]}]="$DESTDIR/${file}"
	mount -B "$file" "$DESTDIR/${file}"
    done
}

rpacman() {
    pacman --cachedir /var/cache/pacman/pkg -r "$DESTDIR" --noconfirm "$@"
}

init_dest() {
    pacman -Sy --noconfirm

    mkdir -p "$DESTDIR"/var/lib/pacman
    cp -a /var/lib/pacman/sync "$DESTDIR"/var/lib/pacman/

    mkdir -p "$DESTDIR"/dev
    cp -a /dev/{null,zero,urandom,tty,ptmx} "$DESTDIR"/dev/

    bind_dirs

    rpacman -S --needed base base-devel
    if [[ ${#PACKAGES[@]} > 0 ]]; then
	rpacman -S --needed "${PACKAGES[@]}"
    fi

    grep -q '^[^#]' "$DESTDIR/etc/pacman.d/mirrorlist" \
	|| sed -ie "\|http://mirrors.cat.pdx.edu/|s/^#//" \
	    "$DESTDIR/etc/pacman.d/mirrorlist"

    rm -r "$DESTDIR/var/tmp"
    ln -s ../tmp "$DESTDIR/var/tmp"

    bind_files
}

setup_yaourt() {
    local pkg

    if rpacman -Qmq | egrep -q '^yaourt$'; then
	return
    fi

    chroot "$DESTDIR" sh -c \
	"pacman-key --init"

    chroot "$DESTDIR" sh -c \
	"yes | pacman-key --populate archlinux"
    
    chroot "$DESTDIR" sh -c \
        "pacman-key --lsign-key 1EB2638FF56C0C53"

    for pkg in package-query yaourt; do
	wget -O- "http://aur.archlinux.org/packages/${pkg:0:2}/${pkg}/${pkg}.tar.gz" \
	    | tar -C "$DESTDIR/tmp" -xzf -
	chroot "$DESTDIR" sh -c \
	    "set -x; cd /tmp/$pkg && makepkg --asroot -si --noconfirm"
    done
}

setup_aur() {
    local pkg

    local -A installed
    while read pkg; do
	installed[$pkg]=1
    done < <(rpacman -Qmq)

    local -a toinstall
    for pkg in "${AUR[@]}"; do
	if [[ -z ${installed[$pkg]} ]]; then
	    toinstall[${#toinstall[@]}]=$pkg
	fi
    done

    if [[ ${#toinstall[@]} > 0 ]]; then
	HOME=/root chroot "$DESTDIR" yaourt --noconfirm -S "${toinstall[@]}"
    fi
    HOME=/root chroot "$DESTDIR" yaourt --noconfirm -Sau
}

setup_init() {
    local dir=${0%/*} init foundit=
    for init in "$dir/cjail-init" /usr/lib/cjail/init; do
	if [[ -x $init ]]; then
	    foundit=1
	    cp "$init" "$DESTDIR"/init
	    chmod 04500 "$DESTDIR"/init
	    break
	fi
    done

    if [[ -z $foundit ]]; then
	echo "cannot find cjail-init" >&2
	exit 1
    fi
}

if [[ $UID != 0 ]]; then
    echo This should be done as root
    exit 1
fi

if [[ -n $STARTSHELL ]]; then
    if ! test -r "$BASEDIR/.cjail"; then
	echo "$BASEDIR: not a cjail (must create it before using -s)" >&2
	exit 1
    fi
    bind_dirs
    bind_files
    chroot "$DESTDIR" bash
    exit
fi

init_dest
setup_yaourt
setup_aur
setup_init

mkdir -p "$READONLY"
mkdir -p "$DESTDIR/root/oldroot"
touch "$BASEDIR/.cjail"

echo ""
echo "=============="
echo "CJail created!"

